# Generated by Django 2.2.12 on 2021-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='field',
            field=models.CharField(choices=[('F', 'Football'), ('V', 'Volleyball'), ('B', 'Basketball'), ('B', 'Badminton')], max_length=250),
        ),
    ]
